"""Auto-reapply persistence — keep the active profile's mapping alive across:

* **login** — an XDG autostart entry runs ``--apply-active`` once.
* **replug / hotplug** — an optional ``systemd --user`` service runs ``--watch``, which
  reapplies whenever the Wacom device reappears.

No root, no ``/etc`` udev rules: everything lives under the user's config/home. The
``render_*`` methods are pure (return file contents) so they can be unit-tested without
touching the real system; :meth:`install` / :meth:`uninstall` do the side effects.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

SERVICE_NAME = "wacom-control-panel-watch.service"
AUTOSTART_NAME = "wacom-control-panel-apply.desktop"


def _config_home() -> Path:
    return Path(os.environ.get("XDG_CONFIG_HOME") or (Path.home() / ".config"))


class Persistence:
    """Generates and installs the login + hotplug reapply hooks."""

    def __init__(
        self,
        python: str | None = None,
        config_home: Path | None = None,
        app_dir: Path | None = None,
    ) -> None:
        self.python = python or sys.executable
        self.config_home = config_home or _config_home()
        self.app_dir = app_dir or (self.config_home / "wacom-control-panel")

    # ---- paths ------------------------------------------------------------
    @property
    def apply_script(self) -> Path:
        return self.app_dir / "apply.sh"

    @property
    def autostart_file(self) -> Path:
        return self.config_home / "autostart" / AUTOSTART_NAME

    @property
    def systemd_unit(self) -> Path:
        return self.config_home / "systemd" / "user" / SERVICE_NAME

    # ---- rendering (pure) -------------------------------------------------
    def render_apply_script(self) -> str:
        return (
            "#!/usr/bin/env bash\n"
            "# Generated by Wacom Control Panel — reapplies the active profile mapping.\n"
            f'exec "{self.python}" -m wacom_panel --apply-active\n'
        )

    def render_autostart(self) -> str:
        return (
            "[Desktop Entry]\n"
            "Type=Application\n"
            "Name=Wacom Control Panel (apply mapping)\n"
            f"Exec={self.apply_script}\n"
            "NoDisplay=true\n"
            "X-GNOME-Autostart-enabled=true\n"
        )

    def render_systemd_unit(self) -> str:
        return (
            "[Unit]\n"
            "Description=Wacom Control Panel — reapply tablet mapping on hotplug\n"
            "After=graphical-session.target\n"
            "PartOf=graphical-session.target\n"
            "\n"
            "[Service]\n"
            "Type=simple\n"
            f'ExecStart={self.python} -m wacom_panel --watch\n'
            "Restart=on-failure\n"
            "RestartSec=3\n"
            "\n"
            "[Install]\n"
            "WantedBy=default.target\n"
        )

    # ---- state ------------------------------------------------------------
    def is_installed(self) -> bool:
        return self.autostart_file.exists()

    # ---- side effects -----------------------------------------------------
    def install(self, *, enable_watch: bool = True) -> list[str]:
        """Write hooks and (best-effort) enable the systemd user service.

        Returns a list of human-readable notes about anything that needed manual attention.
        """
        notes: list[str] = []
        self._write(self.apply_script, self.render_apply_script())
        self.apply_script.chmod(0o755)
        self._write(self.autostart_file, self.render_autostart())
        self._write(self.systemd_unit, self.render_systemd_unit())

        if enable_watch:
            if not self._systemctl("daemon-reload") or not self._systemctl(
                "enable", "--now", SERVICE_NAME
            ):
                notes.append(
                    "Could not enable the systemd --user watcher automatically. "
                    f"Run: systemctl --user enable --now {SERVICE_NAME}"
                )
        return notes

    def uninstall(self) -> None:
        self._systemctl("disable", "--now", SERVICE_NAME)
        for path in (self.autostart_file, self.systemd_unit, self.apply_script):
            path.unlink(missing_ok=True)
        self._systemctl("daemon-reload")

    # ---- helpers ----------------------------------------------------------
    @staticmethod
    def _write(path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)

    @staticmethod
    def _systemctl(*args: str) -> bool:
        try:
            subprocess.run(
                ["systemctl", "--user", *args],
                check=True, capture_output=True, text=True,
            )
            return True
        except (FileNotFoundError, subprocess.CalledProcessError):
            return False
