"""Install / uninstall the ring daemon — the one part of the app that needs privilege.

The ring daemon needs to read the pad input node (``input`` group) and write ``/dev/uinput``
(a udev rule). Those are the *only* root-touching actions in the whole project, so they live
here, isolated, and are **fully reversible**:

* a single self-contained udev rule file we own outright;
* adding the user to ``input`` **only if they aren't already** — recorded in a marker file so
  :meth:`uninstall` removes the membership *only* when we were the ones who added it.

The ``systemd --user`` service that runs ``--ring-daemon`` needs no root and is managed here too
(mirroring :class:`wacom_panel.core.persistence.Persistence`). All ``render_*`` methods are pure
strings so they unit-test without touching the system; the privileged step is funnelled through
one injectable ``runner`` for the same reason.
"""

from __future__ import annotations

import getpass
import grp
import os
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path

RING_SERVICE_NAME = "wacom-control-panel-ring.service"
UDEV_RULE_PATH = Path("/etc/udev/rules.d/70-wacom-uinput.rules")
MARKER_NAME = "ring-daemon-added-input-group"

# A privileged runner takes a bash script and returns True on success. Default uses pkexec/sudo.
Runner = Callable[[str], bool]


def _config_home() -> Path:
    return Path(os.environ.get("XDG_CONFIG_HOME") or (Path.home() / ".config"))


def _default_runner(script: str) -> bool:
    """Run ``script`` as root via pkexec (GUI prompt) or sudo (terminal). False if neither works."""
    for launcher in (["pkexec", "bash", "-c", script], ["sudo", "bash", "-c", script]):
        try:
            subprocess.run(launcher, check=True)
            return True
        except FileNotFoundError:
            continue  # this launcher isn't installed; try the next
        except subprocess.CalledProcessError:
            return False  # launcher ran but the user cancelled / it failed
    return False


def user_in_input_group(user: str | None = None) -> bool:
    """True if ``user`` is already a member of the ``input`` group (nothing to add)."""
    user = user or getpass.getuser()
    try:
        return user in grp.getgrnam("input").gr_mem
    except KeyError:
        return True  # no 'input' group on this system — don't try to add to it


class RingSetup:
    """Reversible installer for the ring daemon's permissions + user service."""

    def __init__(
        self,
        python: str | None = None,
        config_home: Path | None = None,
        app_dir: Path | None = None,
        user: str | None = None,
        runner: Runner | None = None,
    ) -> None:
        self.python = python or sys.executable
        self.config_home = config_home or _config_home()
        self.app_dir = app_dir or (self.config_home / "wacom-control-panel")
        self.user = user or getpass.getuser()
        self._run_privileged = runner or _default_runner

    # ---- paths ------------------------------------------------------------
    @property
    def systemd_unit(self) -> Path:
        return self.config_home / "systemd" / "user" / RING_SERVICE_NAME

    @property
    def marker(self) -> Path:
        return self.app_dir / MARKER_NAME

    # ---- rendering (pure) -------------------------------------------------
    def render_udev_rule(self) -> str:
        return (
            "# Generated by Wacom Control Panel — lets the ring daemon emit synthetic scroll.\n"
            'KERNEL=="uinput", SUBSYSTEM=="misc", MODE="0660", GROUP="input", '
            'OPTIONS+="static_node=uinput"\n'
        )

    def render_systemd_unit(self) -> str:
        return (
            "[Unit]\n"
            "Description=Wacom Control Panel — touch-ring scroll daemon\n"
            "After=graphical-session.target\n"
            "PartOf=graphical-session.target\n"
            "\n"
            "[Service]\n"
            "Type=simple\n"
            f"ExecStart={self.python} -m wacom_panel --ring-daemon\n"
            "Restart=on-failure\n"
            "RestartSec=3\n"
            "\n"
            "[Install]\n"
            "WantedBy=default.target\n"
        )

    def render_install_script(self, *, add_group: bool) -> str:
        lines = [
            "set -e",
            f"cat > {UDEV_RULE_PATH} <<'EOF'",
            self.render_udev_rule().rstrip("\n"),
            "EOF",
            "udevadm control --reload-rules",
            "udevadm trigger /dev/uinput || true",
        ]
        if add_group:
            lines.append(f"usermod -aG input {self.user}")
        return "\n".join(lines) + "\n"

    def render_uninstall_script(self, *, remove_group: bool) -> str:
        lines = [
            f"rm -f {UDEV_RULE_PATH}",
            "udevadm control --reload-rules",
        ]
        if remove_group:
            lines.append(f"gpasswd -d {self.user} input || true")
        return "\n".join(lines) + "\n"

    # ---- state ------------------------------------------------------------
    def is_installed(self) -> bool:
        return self.systemd_unit.exists()

    # ---- side effects -----------------------------------------------------
    def install(self) -> list[str]:
        """Grant permissions + install the user service. Returns human-readable notes."""
        notes: list[str] = []
        add_group = not user_in_input_group(self.user)

        if not self._run_privileged(self.render_install_script(add_group=add_group)):
            notes.append(
                "Could not apply the privileged setup (udev rule + input group). "
                "Re-run with pkexec/sudo available, or apply it manually."
            )
            return notes

        if add_group:
            self._write(self.marker, "")  # remember we added the membership
            notes.append(
                f"Added '{self.user}' to the 'input' group — log out and back in for it to "
                "take effect."
            )

        # User service (no root needed).
        self._write(self.systemd_unit, self.render_systemd_unit())
        if not self._systemctl("daemon-reload") or not self._systemctl(
            "enable", "--now", RING_SERVICE_NAME
        ):
            notes.append(
                "Could not enable the ring daemon service automatically. "
                f"Run: systemctl --user enable --now {RING_SERVICE_NAME}"
            )
        return notes

    def uninstall(self) -> list[str]:
        """Remove the service + permissions, reverting the group add only if we made it."""
        notes: list[str] = []
        self._systemctl("disable", "--now", RING_SERVICE_NAME)
        self.systemd_unit.unlink(missing_ok=True)
        self._systemctl("daemon-reload")

        remove_group = self.marker.exists()
        if not self._run_privileged(self.render_uninstall_script(remove_group=remove_group)):
            notes.append(
                "Could not remove the udev rule automatically; delete "
                f"{UDEV_RULE_PATH} manually."
            )
        else:
            self.marker.unlink(missing_ok=True)
            if remove_group:
                notes.append(
                    f"Removed '{self.user}' from the 'input' group (we had added it). "
                    "Log out and back in to finish."
                )
        return notes

    # ---- helpers ----------------------------------------------------------
    @staticmethod
    def _write(path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)

    @staticmethod
    def _systemctl(*args: str) -> bool:
        try:
            subprocess.run(
                ["systemctl", "--user", *args],
                check=True, capture_output=True, text=True,
            )
            return True
        except (FileNotFoundError, subprocess.CalledProcessError):
            return False
